# Generated by Django 3.2.4 on 2021-06-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210628_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='carrousels', to='blog.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrousel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='carrousels', to='blog.Tag'),
        ),
    ]
