# Generated by Django 3.2.4 on 2021-06-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210628_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrousel',
        ),
    ]
