# Generated by Django 3.2.4 on 2021-06-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_carrousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_carrousel',
            field=models.BooleanField(default=False, verbose_name='Carrousel'),
        ),
    ]
